spring:
  profiles:
    active:
    - dev

---

server:
  port: 8201
spring:
  profiles: dev
  application:
    name: microservicecloud-config-client
eureka:
  client:
    service-url: http://eureka7002.com:7002/eureka/

---
server:
  port: 8202
spring:
  profiles: test
  application:
    name: microservicecloud-config-client
eureka:
  client:
    service-url: http://eureka7003.com:7003/eureka/